{% set name = "jupyterpack" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 993383cf9600540f6cee741bcfc6e34e5ceca12fa9aaf5b72487158e1a635afe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - nodejs
    - pip
    - jupyterlab >=4.0.0,<5
    - hatchling >=1.5.0
    - hatch-nodejs-version
    - hatch-jupyter-builder >=0.5
  run:
    - python >={{ python_min }}

test:
  imports:
    - jupyterpack
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/trungleduc/jupyterpack
  summary: 'A JupyterLite extension to serve in-browser Python and Javascript web application'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - trungleduc
