{% set name = "jupyterpack" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e01461d5f969eda4ec398001de35035cf22c70bc81b872b30f4a98fc5b821f88

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - nodejs
    - pip
    - jupyterlab >=4.0.0,<5
    - hatchling >=1.5.0
    - hatch-nodejs-version
    - hatch-jupyter-builder >=0.5
  run:
    - python >={{ python_min }}
    - httpx
    - tornado
    - starlette
    - numpy
    - pandas
    - specta >=0.4.6

test:
  imports:
    - jupyterpack
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/trungleduc/jupyterpack
  summary: 'A JupyterLite extension to serve in-browser Python and Javascript web application'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - trungleduc
