{% set name = "jupyterpack" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ec7d8776bf11aae157a5b6fe481043a0da55cf5fed4a0c9a453e9e4f1326fad9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - nodejs
    - pip
    - jupyterlab >=4.0.0,<5
    - hatchling >=1.5.0
    - hatch-nodejs-version
    - hatch-jupyter-builder >=0.5
  run:
    - python >={{ python_min }}
    - httpx
    - tornado
    - starlette
    - numpy
    - pandas

test:
  imports:
    - jupyterpack
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/trungleduc/jupyterpack
  summary: 'A JupyterLite extension to serve in-browser Python and Javascript web application'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - trungleduc
